# Generated by Django 5.0.1 on 2024-01-23 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='the name of the movie', max_length=100)),
                ('date', models.DateField(verbose_name='Date the movie was released')),
            ],
        ),
    ]
